### PR TITLE
Suggested fix to default barcode issue

### PR DESCRIPTION
**Pull request by anematode**
Creates a variable DEFAULT_BARCODE == "95000000" for convenience, and changes it from "95012345" which resolves to a (potentially former) PAUSD student.

### CODE REVIEW

**Comment by anematode** [comment]
Fixes #81 .

**Comment by anematode** [comment]
@SheepTester

**Comment by Velosify** [comment]
Alternatively just make the bar a solid black and/or don’t show the number but instead insert (in relatively translucent text) “insert is here”

**Comment by SheepTester** [comment]
lol you cleaned up my code partly, scary!

**Comment by SheepTester** [comment]
The changes won't be pushed onto UGWA yet until I build index.html, which I might do later today

**Pull request merged**
