### PR TITLE
Modernize UGWA's code somewhat

### PR DESCRIPTION
**Pull request by SheepTester**
A multi-stage process:

- [x] Use StandardJS

- [x] Use ES modules

- [x] Use Rollup ~~and Babel~~ to build UGWA

- [x] Betterify l10n system (detect only what is needed; support for placeholders or whatever)

- [x] Clean up code somewhat (ie, reduce redundancy in lists.js)

### CODE REVIEW

**Comment by SheepTester** [comment]
Don't forget to test:

- Ugwita (altScheduleGenerator.js was made into an ES module)

- Non-English languages (now uses dynamic import)

**Comment by SheepTester** [comment]
I would like to clean up schedule.js too, and then after that it is imperative that the built versions be removed.

**Comment by SheepTester** [comment]
NAH

Time to MERGE

**Comment by anematode** [comment]
HUZZAH

**Pull request merged**
