### PR TITLE
Create schedulefetcher.html

### PR DESCRIPTION
**Pull request by PooleHenry**
This is a little bit of html and javascript that might be useful. It displays the day at the top, and shows the daily normal schedule. Probably should have themes and styles added to it.

### CODE REVIEW

**Comment by PooleHenry** [comment]
Oh wait
nvm

**Comment by SheepTester** [comment]
What was wrong?

**Comment by PooleHenry** [comment]
I realized you already had created one

**Comment by SheepTester** [comment]
Oh. That's fine; we can never have too many schedules 🐒

🙈 🙉 🙊

**Pull request closed without merging**
